menu:
- {name: 'people', url: '/people'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Penghao Xiao', role: 'Primary Investigator', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', address: 'Halifax, NS, Canada', email: 'pxiao@dal.ca', phone: '(902) 494-2340', office: 'Dunn Building 230', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Shivam Beniwal', role: 'PhD Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'Shivam.Beniwal@dal.ca', office: 'Dunn Building 243', image: 'assets/img/shivam-beniwal.jpg', url: 'shivam-beniwal'}
- {name: 'Harold Smith Perez', role: 'PhD Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'hsmithperez@dal.ca', office: 'Dunn Building 243', image: 'assets/img/harold.png', url: 'harold_smith'}
- {name: 'Ziyi Zhang', role: 'PhD Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'zy590554@dal.ca', office: 'Dunn Building 243', image: 'assets/img/ziyi_zhang.jpeg', url: 'ziyi_zhang'}
- {name: 'Owen Sullivan', role: 'Undergraduate Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'owensullivan@dal.ca', image: 'assets/img/owenpic.jpeg'}

alumni:
- {name: 'Yi Wang', role: 'Undergraduate Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'wangyi@dal.ca', office: 'Dunn Building 320', image: 'assets/img/YiWang.jpg', url: 'Yi-Wang'}
- {name: 'Courtney Slaunwhite', role: 'DISP Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'cr550044@dal.ca', image: 'assets/img/cs_Image.jpeg', url: 'courtney_slaunwhite'}
- {name: 'Talia Field', role: 'DISP Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'tl903393@dal.ca', image: 'assets/img/IMG_6615.jpg', url: 'talia_field'}
- {name: 'Shraddha Singh', role: 'Undergraduate Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'sh913738@dal.ca', image: 'assets/img/Person_Image_Placeholder.png'}
- {name: 'Achinthya Krishna', role: 'MITACS Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'ac236968@dal.ca', image: 'assets/img/achinthya-krishna.jpg'}
- {name: 'Minjoon Park', role: 'Intern', email: 'mn812994@dal.ca', image: 'assets/img/Person_Image_Placeholder.png', url: 'minjoon_park'}

courses:
- {name: 'PHYC2050', url: 'PHYC2050'}

social:
- {icon: 'github', link: 'https://github.com/Penghao-Xiao'}
- {icon: 'twitter', link: 'https://twitter.com/DrPenghao'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/penghao-xiao-937a6362'}

contacts:
- {name: 'Dr. Penghao Xiao', title: 'Assitant Professor', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', institution_address: 'Halifax, NS, Canada', phone: '(902) 494-2340', email: 'pxiao@dal.ca or xiaopenghao1 at gmail.com', office: 'Dunn Building 230', image: 'assets/img/contact.png',}
