menu:
- {name: 'people', url: '/people'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Penghao Xiao', role: 'Primary Investigator', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', address: 'Halifax, NS, Canada', email: 'pxiao@dal.ca', phone: '(902) 494-2340', office: 'Dunn Building 230', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Yi Wang', role: 'Undergraduate Student', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', email: 'wangyi@dal.ca', office: 'Dunn Building 320', image: 'assets/img/YiWang.jpg', url: 'Yi-Wang'}

courses:
- {name: 'PHYC4230', url: 'PHYC4230'}

social:
- {icon: 'github', link: 'https://github.com/Penghao-Xiao'}
- {icon: 'twitter', link: 'https://twitter.com/DrPenghao'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/penghao-xiao-937a6362'}

contacts:
- {name: 'Dr. Penghao Xiao', title: 'Assitant Professor', department: 'Physics & Atmospheric Science', institution: 'Dalhousie University', institution_address: 'Halifax, NS, Canada', phone: '(902) 494-2340', email: 'pxiao@dal.ca', office: 'Dunn Building 230'}
